version: "3.9"

services:
  postgres:
    image: bitnami/postgresql
    container_name: manager_postgres
    volumes:
      - "./migrations/postgres:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: manager
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - microservices

  app:
    image: mealekks/fam-manager-app:latest
    container_name: manager_app
    ports:
      - "5051:5051"
    networks:
      - microservices
    depends_on:
      - postgres
    restart: always

networks:
  microservices:
    name: microservices
